# Define limit number of connections
events {
    worker_connections 1024;
}

# HTTP global setting
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
		# IPv4
        listen 443 ssl;
		# IPv6
        listen [::]:443 ssl;

        server_name yingzhan.42.fr;

        # SSL setting
		# Dont use insecure encrypted algorithm
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Root directory
        root /var/www/html;
        index index.php index.html index.htm;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        # PHP forwarding
        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        # Static files
        location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg)$ {
            # Cookie
			expires max;
            # Not write 404 to logs
			log_not_found off;
        }
    }
}