# Use penultimate stable Debian as base image
From debian:bookworm
# Install Nginx and OpenSSL
RUN apt-get update && apt-get install -y \
    nginx \
    openssl \
    && rm -rf /var/lib/apt/lists/*
# Create SSL certificate directory
RUN mkdir -p /etc/nginx/ssl
# Generate Self-signed certificate -x509
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/nginx.key \
    -out /etc/nginx/ssl/nginx.crt \
    -subj "/C=DE/ST=State/L=City/O=42/CN=yingzhan.42.fr"
# Copy nginx conf to system directory
COPY conf/nginx.conf /etc/nginx/nginx.conf
EXPOSE 443
# Run Nginx in frontend
CMD ["nginx", "-g", "daemon off;"]