# Disable anonymous user login
anonymous_enable=NO

# Enable local user login
local_enable=YES

# Enable uploading files
write_enable=YES

# Default mode of uploading files
local_umask=022

# Enable passive mode
pasv_enable=YES

# Passive mode port range
pasv_min_port=21100
pasv_max_port=21110

# Running in frontend
listen=YES

# Not use IPv6
listen_ipv6=NO

# Secure chroot dir
secure_chroot_dir=/var/run/vsftpd/empty

# Allow write access in dir
allow_writeable_chroot=YES